name: Sayhi Npm

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  Test-Npm-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: sayhi-npm

      - name: Check release_created
        run: echo "${{ steps.release.outputs.release_created }}"    
            
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@lynntu'
        if: ${{ steps.release.outputs.release_created }}   

      - name: Install dependencies
        run: npm install  
        if: ${{ steps.release.outputs.release_created }}  

      # Publish to npm
      - name: Npm Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}  

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lynntu'
        if: ${{ steps.release.outputs.release_created }}      

      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        if: ${{ steps.release.outputs.release_created }}    